services:
  db:
    image: mysql:8.0
    command: --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION --max_allowed_packet=1073741824 --group_concat_max_len=1000000
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_SQL}
      MYSQL_DATABASE: ${DB_SQL}
    ports:
      - '${PORT_SQL}:3306'
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8084:80'
    environment:
      PMA_HOST: db
      PMA_USER: ${USER_SQL}
      PMA_PASSWORD: ${PASSWORD_SQL}
  redis:
    image: redis
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]
volumes:
  db_data: {}